---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install alacritty
    community.general.pacman:
      name: alacritty
      state: latest

  - name: install emacs
    community.general.pacman:
      name: emacs
      state: latest

  - name: install fish
    community.general.pacman:
      name: fish
      state: latest

  - name: install git
    community.general.pacman:
      name: git
      state: latest

  - name: install i3-gaps
    community.general.pacman:
      name: i3-gaps
      state: latest

  - name: install picom
    community.general.pacman:
      name: picom
      state: latest
