---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install alacritty
    community.general.pacman:
      name: alacritty
      state: latest

  - name: install emacs
    community.general.pacman:
      name: emacs
      state: latest

  - name: install fish
    community.general.pacman:
      name: fish
      state: latest

  - name: install git
    community.general.pacman:
      name: git
      state: latest

  - name: install i3-wm
    community.general.pacman:
      name: i3-wm
      state: latest

  - name: install picom
    community.general.pacman:
      name: picom
      state: latest

  - name: install polybar
    community.general.pacman:
      name: polybar
      state: latest

  - name: install starship
    community.general.pacman:
      name: starship
      state: latest

  - name: install exa
    community.general.pacman:
      name: exa
      state: latest

  - name: configure alacritty
    become_user: flaviogf
    ansible.builtin.copy:
      src: alacritty/.alacritty.yml
      dest: /home/flaviogf/.alacritty.yml
      owner: flaviogf
      group: flaviogf

  - name: configure emacs
    become_user: flaviogf
    ansible.builtin.copy:
      src: emacs/init.el
      dest: /home/flaviogf/.emacs.d/init.el
      owner: flaviogf
      group: flaviogf

  - name: configure fish
    become_user: flaviogf
    ansible.builtin.copy:
      src: fish/config.fish
      dest: /home/flaviogf/.config/fish/config.fish
      owner: flaviogf
      group: flaviogf

  - name: configure git
    become_user: flaviogf
    ansible.builtin.copy:
      src: git/.gitconfig
      dest: /home/flaviogf/.gitconfig
      owner: flaviogf
      group: flaviogf

  - name: configure i3
    become_user: flaviogf
    ansible.builtin.copy:
      src: i3/config
      dest: /home/flaviogf/.config/i3/config
      owner: flaviogf
      group: flaviogf

  - name: configure neovim
    become_user: flaviogf
    ansible.builtin.copy:
      src: nvim/init.lua
      dest: /home/flaviogf/.config/nvim/init.lua
      owner: flaviogf
      group: flaviogf

  - name: configure picom
    become_user: flaviogf
    ansible.builtin.copy:
      src: picom/picom.conf
      dest: /home/flaviogf/.config/picom/picom.conf
      owner: flaviogf
      group: flaviogf

  - name: configure polybar
    become_user: flaviogf
    ansible.builtin.copy:
      src: polybar/config.ini
      dest: /home/flaviogf/.config/polybar/config.ini
      owner: flaviogf
      group: flaviogf

  - name: configure polybar launcher
    become_user: flaviogf
    ansible.builtin.copy:
      src: polybar/launch.sh
      dest: /home/flaviogf/.config/polybar/launch.sh
      owner: flaviogf
      group: flaviogf
      mode: 0744

  - name: configure polybar scripts
    become_user: flaviogf
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /home/flaviogf/.config/polybar/scripts/
      owner: flaviogf
      group: flaviogf
      mode: 0744
    with_fileglob:
      - polybar/scripts/*

  - name: configure starship
    become_user: flaviogf
    ansible.builtin.copy:
      src: starship/starship.toml
      dest: /home/flaviogf/.config/starship.toml
      owner: flaviogf
      group: flaviogf

  - name: configure xorg
    become_user: flaviogf
    ansible.builtin.copy:
      src: xorg/.xinitrc
      dest: /home/flaviogf/.xinitrc
      owner: flaviogf
      group: flaviogf
