"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[directory]
read_only = " "

[docker_context]
symbol = " "

[gcloud]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[line_break]
disabled = true

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "
