"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[character]
error_symbol = "[λ](bold #ff5555)"
success_symbol = "[λ](bold #50fa7b)"

[directory]
format = "[$path ]($style)"
style = "bold #50fa7b"

[line_break]
disabled = true

[username]
format = "[$user ]($style)"
show_always = true
style_user = "bold #8be9fd"