#!/bin/env ruby

# frozen_string_literal: true

module Emacs
  class Client
    def eval(expression)
      `emacsclient --socket=emacs --eval '#{expression}' 2> /dev/null`
    end

    def org_timer_value_string
      '(org-timer-value-string)'
    end
  end
end

class Pomodoro
  def initialize(io)
    @io = io
  end

  def output(hour = '00', minutes = '00', seconds = '00')
    @io.printf("%02d:%02d:%02d\n", hour, minutes, seconds)
  end
end

emacsclient = Emacs::Client.new
value = emacsclient.eval(emacsclient.org_timer_value_string)
match_data = value.match(/(\d{1,2}):(\d{1,2}):(\d{1,2})/)

pomodoro = Pomodoro.new($stdout)

if match_data
  pomodoro.output(*match_data.captures)
else
  pomodoro.output
end
